{{- if and (eq .Capabilities.KubeVersion.Major "1") ( ge  ( trimSuffix "+" .Capabilities.KubeVersion.Minor ) "14") }}
---

################# CSI Driver ###########
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.hpe.com
spec:
  podInfoOnMount: true
  {{- if and (eq .Capabilities.KubeVersion.Major "1") ( ge  ( trimSuffix "+" .Capabilities.KubeVersion.Minor ) "16") }}
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
  {{- end }}
{{- end }}