{{- if semverCompare ">=1.14.0" .Capabilities.KubeVersion.Version }}
---

################# CSI Driver ###########
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: csi.hpe.com
spec:
  podInfoOnMount: true
  {{- if semverCompare ">=1.16.0" .Capabilities.KubeVersion.Version }}
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
  {{- end }}
{{- end }}