# (C) Copyright 2019-2021 Hewlett Packard Enterprise Development LP
---
### CSP Service ###
kind: Service
apiVersion: v1
metadata:
  name: cv-csp-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: cv-csp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: cv-csp

---
### CSP deployment ###
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cv-csp
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: cv-csp
  replicas: 1
  template:
    metadata:
      labels:
        app: cv-csp
    spec:
      serviceAccount: hpe-csp-sa
      {{- if and (eq .Capabilities.KubeVersion.Major "1") ( ge  ( trimSuffix "+" .Capabilities.KubeVersion.Minor ) "17") }}
      priorityClassName: system-cluster-critical
      {{- end }}
      containers:
        - name: cv-csp
          {{- if .Values.registry }}
          image: {{ .Values.registry }}/hpestorage/cv-csp:v1.0.0-beta
          {{- else }}
          image: quay.io/hpestorage/cv-csp:v1.0.0-beta
          {{- end }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          env:
          - name: API_HOST
            value: "https://prod.cloudvolumes.hpe.com"
          ports:
          - containerPort: 8080
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 30
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 30

