apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-pre-install"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed 
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-pre-install"
      labels:
        app.kubernetes.io/name: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Validating Secret..."
            {{ include "hpe-csi-storage.chapSecretValidation" . }}
            echo "Validation successful."
