{{ if .Values.storageClass.create -}}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: {{ .Values.storageClass.name }}
   labels:
     plugin: {{ .Release.Name }}
   {{- if .Values.storageClass.defaultClass }}
   annotations:
     storageclass.kubernetes.io/is-default-class: "true"
   {{- end }}
provisioner: csi.hpe.com
{{- if semverCompare ">=1.14.0" .Capabilities.KubeVersion.GitVersion }}
allowVolumeExpansion: {{ .Values.allowVolumeExpansion }}
{{- end }}
parameters:
   description: {{ .Values.volumeDescription }}
   csi.storage.k8s.io/fstype: {{ .Values.fsType }}
   csi.storage.k8s.io/provisioner-secret-name: nimble-secret
   csi.storage.k8s.io/provisioner-secret-namespace: kube-system
   csi.storage.k8s.io/controller-publish-secret-name: nimble-secret
   csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
   csi.storage.k8s.io/node-stage-secret-name: nimble-secret
   csi.storage.k8s.io/node-stage-secret-namespace: kube-system
   csi.storage.k8s.io/node-publish-secret-name: nimble-secret
   csi.storage.k8s.io/node-publish-secret-namespace: kube-system
   {{- if semverCompare "=1.14.0" .Capabilities.KubeVersion.GitVersion }}
   csi.storage.k8s.io/resizer-secret-name: nimble-secret
   csi.storage.k8s.io/resizer-secret-namespace: nimble-secret
   {{- else if semverCompare ">=1.15.0" .Capabilities.KubeVersion.GitVersion }}
   csi.storage.k8s.io/controller-expand-secret-name: nimble-secret
   csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
   {{- end }}
{{- end }}