{{ if $sc := (lookup "storage.k8s.io/v1" "StorageClass" "" "hpe-standard") -}}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hpe-standard
  labels:
    plugin: {{ .Release.Name }}
  annotations:
    "helm.sh/resource-policy": keep
    {{- range $k, $v := $sc.metadata.annotations }}
    {{ $k }}: {{ $v}}
    {{- end }}
provisioner: csi.hpe.com
{{- if semverCompare ">=1.15.0" .Capabilities.KubeVersion.GitVersion }}
allowVolumeExpansion: {{ $sc.allowVolumeExpansion }}
{{- end }}
parameters:
  {{- range $k, $v := $sc.parameters }}
  {{ $k }}: {{ $v}}
  {{- end }}
{{- end }}
