{{ if .Values.storageClass.create -}}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: {{ .Values.storageClass.name }}
   labels:
     plugin: {{ .Release.Name }}
   {{- if .Values.storageClass.defaultClass }}
   annotations:
     storageclass.kubernetes.io/is-default-class: "true"
   {{- end }}
provisioner: csi.hpe.com
{{- if semverCompare ">=1.15.0" .Capabilities.KubeVersion.GitVersion }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
{{- end }}
parameters:
   description: {{ .Values.storageClass.parameters.volumeDescription }}
   accessProtocol: {{ .Values.storageClass.parameters.accessProtocol }}
   {{- if eq .Values.backendType "hpe3parprimera" }}
   provisioning_type: {{ .Values.storageClass.parameters.provisioningType }}
   cpg: {{ .Values.storageClass.parameters.cpg }}
   csi.storage.k8s.io/fstype: ext4
   {{- else }}
   csi.storage.k8s.io/fstype: {{ .Values.storageClass.parameters.fsType }}
   {{- end }}
   csi.storage.k8s.io/provisioner-secret-name: {{ .Values.backendType }}-secret
   csi.storage.k8s.io/provisioner-secret-namespace: {{ .Release.Namespace }}
   csi.storage.k8s.io/controller-publish-secret-name: {{ .Values.backendType }}-secret
   csi.storage.k8s.io/controller-publish-secret-namespace: {{ .Release.Namespace }}
   csi.storage.k8s.io/node-stage-secret-name: {{ .Values.backendType }}-secret
   csi.storage.k8s.io/node-stage-secret-namespace: {{ .Release.Namespace }}
   csi.storage.k8s.io/node-publish-secret-name: {{ .Values.backendType }}-secret
   csi.storage.k8s.io/node-publish-secret-namespace: {{ .Release.Namespace }}
   {{- if semverCompare ">=1.15.0" .Capabilities.KubeVersion.GitVersion }}
   csi.storage.k8s.io/controller-expand-secret-name: {{ .Values.backendType }}-secret
   csi.storage.k8s.io/controller-expand-secret-namespace: {{ .Release.Namespace }}
   {{- end }}
{{- end }}
