apiVersion: v1
entries:
  hpe-csi-driver:
  - apiVersion: v1
    appVersion: 1.4.0-beta
    created: "2020-12-16T12:51:53.414071-08:00"
    description: A Helm chart for installing the HPE CSI Driver for Kubernetes
    digest: 806f9acad3615c8e9e3ed7ba7ce7111349ff9572e63979323aa553916360f5b9
    home: https://hpe.com/storage/containers
    icon: https://raw.githubusercontent.com/hpe-storage/co-deployments/master/docs/assets/hpedev.png
    keywords:
    - HPE
    - Storage
    - StorageClass
    - CentOS
    - Ubuntu
    - RHEL
    maintainers:
    - email: hpe-containers-dev@hpe.com
      name: raunakkumar
    name: hpe-csi-driver
    sources:
    - https://scod.hpedev.io/csi_driver
    urls:
    - hpe-csi-driver-1.4.0-beta.tgz
    version: 1.4.0-beta
generated: "2020-12-16T12:51:53.412859-08:00"
