# Configuration to deploy the HPE 3PAR Primera Storage CSP service
#
# example usage: kubectl create -f <this_file>

##############################################
############  HPEVolumeInfos CRD  ############
##############################################

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: hpevolumeinfos.storage.hpe.com
spec:
  group: storage.hpe.com
  names:
    kind: HPEVolumeInfo
    plural: hpevolumeinfos
    shortNames:
      - hperdi
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        hpeVolumes:
          description: List of HPE volumes configured for 3PAR/Primera arrays.
          items:
            properties:
              uuid:
                description: The UUID of the volume.
                type: string
              record:
                description: Metadata for the volume.
                type: map[string]string
          type: array
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: hpereplicationdeviceinfos.storage.hpe.com
spec:
  group: storage.hpe.com
  names:
    kind: HPEReplicationDeviceInfo
    plural: hpereplicationdeviceinfos
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        hpeReplicationDeviceInfos:
          description: List of HPE Replicated Arrays configured for 3PAR/Primera arrays.
          items:
            properties:
              targets:
                description: Target Array Details
                type: array
                items:
                  properties:
                    targetName:
                      description: Target Name of the array
                      type: string
                    targetCpg:
                      description: Target CPG of the array
                      type: string
                    targetSnapCpg:
                      description: Target Snap CPG of the array
                      type: string
                    targetSecret:
                      description: Secret of the replicated array
                      type: string
                    targetMode:
                      description: Replication Mode
                      type: string
                    targetSecretNamespace:
                      description: Namespace of secret
                      type: string
                  required:
                    - targetName
                    - targetCpg
                    - targetSecret
                    - targetSecretNamespace
          type: array
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---

#######################################
############  CSP Service  ############
#######################################

kind: Service
apiVersion: v1
metadata:
  name: primera3par-csp-svc
  namespace: hpe-storage
  labels:
    app: primera3par-csp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: primera3par-csp

---

##########################################
############  CSP Deployment  ############
##########################################

kind: Deployment
apiVersion: apps/v1
metadata:
  name: primera3par-csp
  namespace: hpe-storage
spec:
  selector:
    matchLabels:
      app: primera3par-csp
  replicas: 1
  template:
    metadata:
      labels:
        app: primera3par-csp
    spec:
      serviceAccount: hpe-csp-sa
      priorityClassName: system-cluster-critical
      containers:
        - name: primera3par-csp
          image: quay.io/hpestorage/hpe3parprimera-csp:v1.2.0-beta
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: log-dir
              mountPath: /var/log
      volumes:
        - name: log-dir
          hostPath:
            path: /var/log
