# (C) Copyright 2019-2021 Hewlett Packard Enterprise Development LP

# Configuration to deploy the Cloud Volumes Container Storage Provider
#
# example usage: kubectl create -f <this_file>

---

#######################################
############  CSP Service  ############
#######################################

kind: Service
apiVersion: v1
metadata:
  name: cv-csp-svc
  namespace: hpe-storage
  labels:
    app: cv-csp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: cv-csp

---

##########################################
############  CSP Deployment  ############
##########################################
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cv-csp
  namespace: hpe-storage
spec:
  selector:
    matchLabels:
      app: cv-csp
  replicas: 1
  template:
    metadata:
      labels:
        app: cv-csp
    spec:
      serviceAccount: hpe-csp-sa
      priorityClassName: system-cluster-critical
      containers:
        - name: cv-csp
          image: quay.io/hpestorage/cv-csp:v1.0.0-beta
          imagePullPolicy: Always
          env:
          - name: API_HOST
            value: "https://prod.cloudvolumes.hpe.com"
          ports:
          - containerPort: 8080
