# Configuration to deploy the HPE Nimble Storage CSP service
#
# example usage: kubectl create -f <this_file>

---

#######################################
############  CSP Service  ############
#######################################

kind: Service
apiVersion: v1
metadata:
  name: hpe-alletra-6000-and-nimble-csp-svc
  namespace: hpe-storage
  labels:
    app: hpe-alletra-6000-and-nimble-csp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: hpe-alletra-6000-and-nimble-csp

---

##########################################
############  CSP Deployment  ############
##########################################

kind: Deployment
apiVersion: apps/v1
metadata:
  name: hpe-alletra-6000-and-nimble-csp
  namespace: hpe-storage
spec:
  selector:
    matchLabels:
      app: hpe-alletra-6000-and-nimble-csp
  replicas: 1
  template:
    metadata:
      labels:
        app: hpe-alletra-6000-and-nimble-csp
    spec:
      serviceAccountName: hpe-csp-sa
      priorityClassName: system-cluster-critical
      containers:
        - name: hpe-alletra-6000-and-nimble-csp
          image: quay.io/hpestorage/hpe-alletra-6000-and-nimble-csp:v2.0.0-beta
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: log-dir
              mountPath: /var/log
      volumes:
        - name: log-dir
          hostPath:
            path: /var/log
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 30
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 30
