---
# Source: hpe-csi-driver/templates/nimble-csp.yaml
### Alletra 5000/6000 CSP Service ###
kind: Service
apiVersion: v1
metadata:
  name: alletra6000-csp-svc
  namespace: hpe-storage
  labels:
    app: alletra6000-csp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app:  nimble-csp
---
# Source: hpe-csi-driver/templates/nimble-csp.yaml
### Nimble CSP Service ###
kind: Service
apiVersion: v1
metadata:
  name: nimble-csp-svc
  namespace: hpe-storage
  labels:
    app: nimble-csp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: nimble-csp
---
# Source: hpe-csi-driver/templates/nimble-csp.yaml
### CSP deployment ###
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nimble-csp
  namespace: hpe-storage
spec:
  selector:
    matchLabels:
      app: nimble-csp
  replicas: 1
  template:
    metadata:
      labels:
        app: nimble-csp
    spec:
      serviceAccountName: hpe-csp-sa
      priorityClassName: system-cluster-critical
      containers:
        - name: nimble-csp
          image: "quay.io/hpestorage/alletra-6000-and-nimble-csp:v3.0.1"
          resources:
            limits:
              cpu: 2000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          imagePullPolicy: "IfNotPresent"
          env:
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: log-dir
              mountPath: /var/log
      volumes:
        - name: log-dir
          hostPath:
            path: /var/log
