# Configuration to deploy the HPE Nimble Storage CSP service
#
# example usage: kubectl create -f <this_file>

---

#######################################
############  CSP Service  ############
#######################################

kind: Service
apiVersion: v1
metadata:
  name: nimble-csp-svc
  namespace: hpe-storage
  labels:
    app: nimble-csp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: nimble-csp

---

##########################################
############  CSP Deployment  ############
##########################################

kind: Deployment
apiVersion: apps/v1
metadata:
  name: nimble-csp
  namespace: hpe-storage
spec:
  selector:
    matchLabels:
      app: nimble-csp
  replicas: 1
  template:
    metadata:
      labels:
        app: nimble-csp
    spec:
      serviceAccount: hpe-csp-sa
      priorityClassName: system-cluster-critical
      containers:
        - name: nimble-csp
          image: quay.io/hpestorage/nimble-csp:v1.4.0-beta
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: log-dir
              mountPath: /var/log
      volumes:
        - name: log-dir
          hostPath:
            path: /var/log
