apiVersion: v2
name: hpe-array-exporter
version: "1.0.0"
appVersion: "1.0.0"
annotations:
  artifacthub.io/prerelease: "false"
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://hpe-storage.github.io/array-exporter
description: A Helm chart for installing the HPE Storage Array Exporter for Prometheus
icon: https://raw.githubusercontent.com/hpe-storage/co-deployments/master/docs/assets/hpedev.png
maintainers:
- name: rkumpf
  email: hpe-containers-dev@hpe.com
sources:
- https://github.com/hpe-storage/co-deployments
home: https://hpe.com/storage/containers
keywords:
  - HPE
  - Storage
  - Prometheus
