apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hpecsidrivers.storage.hpe.com
spec:
  group: storage.hpe.com
  names:
    kind: HPECSIDriver
    listKind: HPECSIDriverList
    plural: hpecsidrivers
    singular: hpecsidriver
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1
    served: true
    storage: true
