# The HPE Storage Array Exporter for Prometheus uses a Secret to
# identify the target storage system and provide its login
# credentials.
#
# Modify this sample file to:
# - Use a unique name for each storage system
# - Match the namespace where the exporter will be deployed
# - Specify the address, user name, and password for the target
#   storage system
#
# For convenience, a Secret used by the HPE CSI Driver can be
# reused without modification.

---
kind: Secret
apiVersion: v1
metadata:
  name: hpe-backend
  namespace: hpe-storage
stringData:
  address: 192.168.1.1
  username: admin
  password: admin
