# Configuration to deploy the HPE Nimble Storage Container Provider service
#
# example usage: kubectl create -f <this_file>

---

#######################################
############  CP Service  ############
#######################################

kind: Service
apiVersion: v1
metadata:
  name: cv-cp-svc
  namespace: kube-system
  labels:
    app: cv-cp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: cv-cp

---

##########################################
############  CP Deployment  ############
##########################################

kind: Deployment
apiVersion: apps/v1
metadata:
  name: cv-cp
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: cv-cp
  replicas: 1
  template:
    metadata:
      labels:
        app: cv-cp
    spec:
      priorityClassName: system-cluster-critical
      containers:
        - name: cv-cp
          image: store/hpestorage/cv-cp:v3.1.0
          imagePullPolicy: Always
          env:
            - name: CLOUDVOLUMES_PORTAL_SERVER
              valueFrom:
                secretKeyRef:
                  name: hpe-secret
                  key: backend
            - name: CLOUDVOLUMES_PORT
              value: "8080"
            - name: LOG_LEVEL
              value: debug
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: log-dir
              mountPath: /var/log
      volumes:
        - name: log-dir
          hostPath:
            path: /var/log
