# Configuration to deploy the HPE Nimble Storage Container Provider service
#
# example usage: kubectl create -f <this_file>
​
---
​
#######################################
############  CP Service  ############
#######################################
​
kind: Service
apiVersion: v1
metadata:
  name: nimble-cp-svc
  namespace: kube-system
  labels:
    app: nimble-cp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: nimble-cp
​
---
​
##########################################
############  CP Deployment  ############
##########################################
​
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cp-service
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: nimble-cp
  replicas: 1
  template:
    metadata:
      labels:
        app: nimble-cp
    spec:
      containers:
        - name: nimble-cp
          image: hpestorage/cv-cp:canary
          imagePullPolicy: Always
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: CLOUDVOLUMES_PORTAL_SERVER
              value: cloudvolumes.hpe.com
            - name: CLOUDVOLUMES_PORT
              value: "8090"
            - name: LOG_LEVEL
              value: debug
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: log-dir
              mountPath: /var/log
      volumes:
        - name: log-dir
          hostPath:
            path: /var/log