---
apiVersion: v1
kind: Secret
metadata:
  name: hpe-secret
  namespace: kube-system
stringData:
  username: {{ .Values.username }}
  password: {{ .Values.password }}
  backend: {{ .Values.backend }}
  protocol: {{ .Values.protocol }}
