---
apiVersion: v1
kind: Secret
metadata:
  name: hpe-secret
  namespace: kube-system
stringData:
  username: {{ .Values.username }}
  password: {{ .Values.password }}
  {{- if eq .Values.pluginType "cv"}}
  backend: {{ .Values.backend }}
  servicePort: {{ .Values.servicePort | quote }}
  serviceName: {{ .Values.serviceName }}
  protocol: "iscsi"
  {{- else }}
  backend: {{ .Values.backend }}
  protocol: {{ .Values.protocol }}
  {{- end }}
