---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hpe-config
  namespace: kube-system
data:
  volume-driver.json: |-
  {{- if eq .Values.pluginType "nimble"}}
    {{ .Values.nimble.config | toJson | b64enc | quote }}
  {{- else if eq .Values.pluginType "cv"}}
    {{ .Values.cv.config | toJson | b64enc | quote }}
  {{- else }}
    {
      "global":   {},
      "defaults": {
                 "sizeInGiB": 10
                },
      "overrides":{}
    }
  {{- end }}

  {{- if eq .Values.flavor "rancher"}}
  {{ .Values.pluginType }}.json: |-
    {
      "dockerVolumePluginSocketPath": "/host/etc/hpe-storage/{{ .Values.pluginType }}.sock"
    }
  {{- end }}
