---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: hpe-flexvolume-sc
 namespace: default
 labels:
   plugin: {{ .Release.Name }}
provisioner: hpe.com/nimble
parameters:
  description: {{ .Values.volumeDescription }}
  mountConflictDelay: {{ .Values.mountConflictDelay | quote }}
