---
# © Copyright 2025 Hewlett Packard Enterprise Development LP
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.deployment.name }}-role
  labels:
    {{- include "hpe-cosi-driver.labels" . | nindent 4 }}
rules:
- apiGroups: ["objectstorage.k8s.io"]
  resources: ["buckets", "bucketaccesses","buckets/status", "bucketaccesses/status", "bucketclaims", "bucketclaims/status", "bucketaccessclasses"]
  verbs: ["get", "list", "watch", "update", "create", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "delete", "update", "create", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.deployment.name }}-role-binding
  labels:
    {{- include "hpe-cosi-driver.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.deployment.name }}-sa
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.deployment.name }}-role
  apiGroup: rbac.authorization.k8s.io
