---
# © Copyright 2025 Hewlett Packard Enterprise Development LP
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deployment.name }}-sa
  namespace: {{ .Values.Namespace }}
  labels:
    {{- include "hpe-cosi-driver.labels" . | nindent 4 }}
