apiVersion: v1
appVersion: "3.1"
description: A Helm chart for installing the HPE Volume Driver for Kubernetes FlexVolume plugin
icon: https://raw.githubusercontent.com/hpe-storage/co-deployments/master/docs/assets/hpedev.png
maintainers:
- name: shivamerla
  email: hpe-containers-dev@hpe.com
sources:
- https://github.com/hpe-storage/flexvolume-driver
name: hpe-flexvolume-driver
version: 3.1.0
home: https://hpe.com/storage/containers
keywords:
  - HPE
  - Storage
  - StorageClass
  - CentOS
  - Ubuntu
  - CloudVolumes

