apiVersion: v1
appVersion: "3.0"
description: A Helm chart for installing the HPE Volume Driver for Kubernetes FlexVolume plugin
icon: https://raw.githubusercontent.com/hpe-storage/co-deployments/master/docs/assets/hpedev.png
maintainers:
- name: hpe-containers-dev@hpe.com
name: hpe-flexvolume-driver
version: 3.0.0
keywords:
  - HPE
  - Storage
  - StorageClass
  - CentOS
  - Ubuntu
