# Default values for hpe-flexvolume-driver
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#doryd image
dynamicProvisionerTag: 3.0.0
dynamicProvisionerImage: hpestorage/k8s-dynamic-provisioner

#flexvolume plugin image
flexVolumeDriverTag: 3.0.0
flexVolumeDriverImage: hpestorage/flexvolume-driver

#parameters
backend: 10.0.0.1
username: admin
password: admin
protocol: iscsi

#storage class parameters
fsType: xfs
volumeDescription: "volume created by HPE CSI driver"
mountConflictDelay: "150"

#service parameters
# wait seconds for doryd/flexvolume node plugins to start
serviceWaitTime: "10"

#flavor
flavor: kubernetes

#platform for which plugin is being deployed.i.e nimble or cv
pluginType: nimble

#bindMountPath where kubelet bindmounts volume to pod namespace
podsMountDir: /var/lib/kubelet/pods

#volumePluginDir volume plugin directory where kubelet watches for flexvolume plugin
volumePluginDir: /usr/libexec/kubernetes/kubelet-plugins/volume/exec