# Default values for hpe-flexvolume-driver
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#doryd image
dynamicProvisionerTag: v3.0.0
dynamicProvisionerImage: store/hpestorage/k8s-dynamic-provisioner

#flexvolume plugin image
flexVolumeDriverTag: v3.0.0
flexVolumeDriverImage: store/hpestorage/flexvolume-driver

#container-provider image
containerProviderTag: canary
containerProviderImage: hpestorage/cv-cp

#parameters
backend: 192.168.1.1
username: admin
password: admin
protocol: iscsi
servicePort: "8080"
serviceName: cv-cp-svc

#storage class parameters
fsType: xfs
volumeDescription: "Volume created by HPE Volume Driver for Kubernetes FlexVolume Plugin"

#service parameters
# wait seconds for doryd/flexvolume node plugins to start
serviceWaitTime: "10"

#flavor
flavor: kubernetes

#platform for which plugin is being deployed.i.e nimble or cv
pluginType: nimble

#bindMountPath where kubelet bindmounts volume to pod namespace
podsMountDir: /var/lib/kubelet/pods

#volumePluginDir volume plugin directory where kubelet watches for flexvolume plugin
flexVolumeExec: /usr/libexec/kubernetes/kubelet-plugins/volume/exec

## For creating the StorageClass automatically:
storageClass:
  create: true

  ## Set StorageClass as the default StorageClass
  ## Ignored if storageClass.create is false
  defaultClass: false

  ## Set a StorageClass name
  ## Ignored if storageClass.create is false
  name: hpe-standard

## Nimble Storage Config Parameters
nimble:
  config: |-
    {
      "global": {},
      "defaults": {
                "sizeInGiB": 10,
                "limitIOPS": -1,
                "limitMBPS": -1,
                "perfPolicy": "DockerDefault",
                "mountConflictDelay": 120
                },
      "overrides": {}
    }

## Cloud Volumes Config Parameters
cv:
  config: |-
    {
      "global": {
                "snapPrefix": "BaseFor",
                "initiators": ["10.128.0.14", "10.1.0.8", "10.1.0.7"],
                "automatedConnection": true,
                "existingCloudSubnet": "10.1.0.0/24",
                "region": "us-east-1",
                "privateCloud": "vpc-data",
                "cloudComputeProvider": "Google Cloud Platform"
      },
      "defaults": {
                "sizeInGiB": 10,
                "limitIOPS": 1000,
                "description": "Volume provisioned by the HPE Volume Driver for Kubernetes FlexVolume Plugin",
                "perfPolicy": "Other",
                "protectionTemplate": "twicedaily:4",
                "encryption": true,
                "volumeType": "PF",
                "destroyOnRm": true,
                "mountConflictDelay": 120
      },
      "overrides": {
      }
    }
