# A Service Monitor can enable a Prometheus Operator within the cluster
# to discover the HPE CSI Info Metrics Provider for Prometheus as a
# scrape target.
#
# Modify this sample file to:
# - Match the namespace of the hpe-csi-info-metrics-service
# - Match the selector used by the Prometheus Operator installation
# - Customize the scrape configuration, including desired target labels

---
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: hpe-csi-info-metrics-servicemonitor
  namespace: hpe-storage
  labels:
    # A selector for this label is used by a Prometheus Operator
    # installed via OLM
    k8s-app: prometheus
    # A "release" label selector is used by the Helm Kube Prometheus Stack,
    # with the value as the release specified on chart installation
    release: prometheus
spec:
  # Match the namespace of the target CSI Info Metrics service,
  # or omit the namespaceSelector
  namespaceSelector:
    matchNames:
      - hpe-storage
  selector:
    matchLabels:
      app: hpe-csi-info-metrics
  endpoints:
    - port: http-metrics
      scheme: http
      interval: 1m
  # Corresponding labels on the CSI Info Metrics service are added to
  # the scraped metrics
  #targetLabels:
  #  - cluster
