---

#######################################
############  Node driver  ############
#######################################

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: hpe-filex-csi-node
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: hpe-filex-csi-node
  template:
    metadata:
      labels:
        app: hpe-filex-csi-node
        role: hpe-filex-csi
        {{- if .Values.node.labels }}
{{ toYaml .Values.node.labels | indent 8 }}
        {{- end }}
    spec:
      serviceAccountName: hpe-filex-csi-node-sa
      priorityClassName: system-node-critical
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      initContainers:
        - name: hpe-filex-csi-node-init
          image: {{ .Values.images.csiNodeInit | quote }}
          resources:
            {{- toYaml .Values.node.resources | nindent 12 }}
          volumeMounts:
            - name: root-dir
              mountPath: /host
              mountPropagation: "Bidirectional"
            - name: etc-hpe-storage-dir
              mountPath: /etc/hpe-storage
            - name: runsystemd
              mountPath: /run/systemd
            - name: etcsystemd
              mountPath: /etc/systemd/system
          env:
            {{ if .Values.disableNodeConformance -}}
            - name: DISABLE_NODE_CONFORMANCE
              value: "true"
            {{- end }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
      containers:
        - name: csi-node-driver-registrar
          image: {{ .Values.images.csiNodeDriverRegistrar | quote }}
          resources:
            {{- toYaml .Values.node.resources | nindent 12 }}
          args:
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              {{- if .Values.kubeletRootDir }}
              value: {{ .Values.kubeletRootDir }}/plugins/filex.csi.hpe.com/csi.sock
              {{- else }}
              value: /var/lib/kubelet/plugins/filex.csi.hpe.com/csi.sock
              {{- end }}
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: hpe-filex-csi-node-driver
          image: {{ .Values.images.csiNodeDriver | quote }}
          resources:
            {{- toYaml .Values.node.resources | nindent 12 }}
          args :
          - serve
          env:
          - name: X_CSI_PLUGIN_NAME
            value: filex.csi.hpe.com
          - name: X_CSI_VMS_HOST
          - name: X_CSI_ENABLE_VMS_SSL_VERIFICATION
            value: "false"
          - name: X_CSI_DELETION_VIP_POOL_NAME
          - name: X_CSI_DELETION_VIEW_POLICY
          - name: X_CSI_WORKER_THREADS
            value: "10"
          - name: X_CSI_DONT_USE_TRASH_API
            value: "false"
          - name: X_CSI_USE_LOCALIP_FOR_MOUNT
          - name: X_CSI_ATTACH_REQUIRED
            value: "true"
          - name: X_CSI_VMS_TIMEOUT
            value: "15"
          - name: X_CSI_TRUNCATE_VOLUME_NAME
            value: "64"
          - name: CSI_ENDPOINT
            value: unix:///csi/csi.sock
          - name: X_CSI_MODE
            value: node
          - name: X_CSI_NODE_ID
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          volumeMounts:
          - name: pods-mount-dir
          {{- if .Values.kubeletRootDir }}
            mountPath:  {{ .Values.kubeletRootDir }}
          {{- else }}
            mountPath: /var/lib/kubelet
          {{- end }}
            mountPropagation: Bidirectional
          - name: plugin-dir
            mountPath: /csi
          - name: device-dir
            mountPath: /dev
          - name: host-nfsmount-conf-d
            mountPath: /etc/nfsmount.conf.d
      volumes:
      # gl4f
      - hostPath:
        {{ if .Values.kubeletRootDir }}
          path: {{ .Values.kubeletRootDir }}/plugins_registry/
        {{- else }}
          path: /var/lib/kubelet/plugins_registry/
        {{- end }}
          type: DirectoryOrCreate
        name: registration-dir
      - hostPath:
        {{ if .Values.kubeletRootDir }}
          path: {{ .Values.kubeletRootDir }}/plugins/filex.csi.hpe.com
        {{- else }}
          path: /var/lib/kubelet/plugins/filex.csi.hpe.com
        {{- end }}
          type: DirectoryOrCreate
        name: plugin-dir
      - hostPath:
        {{ if .Values.kubeletRootDir }}
          path: {{ .Values.kubeletRootDir }}
        {{- else }}
          path: /var/lib/kubelet
        {{- end }}
          type: Directory
        name: pods-mount-dir
      - hostPath:
          path: /dev
          type: ""
        name: device-dir
      - hostPath:
          path: /etc/nfsmount.conf.d
          type: DirectoryOrCreate
        name: host-nfsmount-conf-d

      # init
      - name: root-dir
        hostPath:
          path: /
      - name: runsystemd
        hostPath:
          path: /run/systemd
      - name: etcsystemd
        hostPath:
          path: /etc/systemd/system
      - name: etc-hpe-storage-dir
        hostPath:
          path: /etc/hpe-storage
      {{- if .Values.node.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.node.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.node.tolerations }}
      tolerations:
{{ toYaml .Values.node.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.node.affinity }}
      affinity:
{{ toYaml .Values.node.affinity | indent 8 }}
      {{- end }}
