---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hpeflexvolumedrivers.storage.hpe.com
spec:
  group: storage.hpe.com
  names:
    kind: HPEFlexVolumeDriver
    listKind: HPEFlexVolumeDriverList
    plural: hpeflexvolumedrivers
    singular: hpeflexvolumedriver
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  subresources:
    status: {}