---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpe-flexvolume-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hpe-flexvolume-operator
  template:
    metadata:
      labels:
        name: hpe-flexvolume-operator
    spec:
      serviceAccountName: default
      containers:
        - name: hpe-flexvolume-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: hpe-flexvolume-operator