####################################################
############  HpeVolumeInfos Crd  ############
####################################################

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: hpevolumeinfos.storage.hpe.com
spec:
  group: storage.hpe.com
  names:
    kind: HPEVolumeInfo
    plural: hpevolumeinfos
  scope: Cluster
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: false  
      schema:
        openAPIV3Schema:
          type: object
          #x-kubernetes-preserve-unknown-fields: true
          properties:
            hpeVolumes:
              description: List of HPE volumes configured for 3PAR/Primera arrays.
              type: object
              items:
                type: object
                properties:
                  uuid:
                    description: The UUID of the node.
                    type: string
          
                  record:
                    description: Metadata for the volume
                    type: object
    - name: v2
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true  
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true

          properties:
            hpeVolumes:
              description: List of HPE volumes configured for 3PAR/Primera arrays.
              type: object
              items:
                type: object
                properties:
                  uuid:
                    description: The UUID of the node.
                    type: string
          
                  record:
                    description: Metadata for the volume
                    type: object                    

status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---

####################################################
############  HpeVolumeGroupInfos Crd  ############
####################################################

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: hpevolumegroupinfos.storage.hpe.com
spec:
  group: storage.hpe.com
  names:
    kind: HPEVolumeGroupInfo
    plural: hpevolumegroupinfos
    shortNames: 
      - hpevgi
  scope: Cluster
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: false 
      schema:       
        openAPIV3Schema:
          type: object
          #x-kubernetes-preserve-unknown-fields: true
          properties:
            hpeVolumeGroupInfos:
              description: List of HPE volume groups configured for 3PAR/Primera arrays.
              items:
                type: object
                properties:
                  uuid:
                    description: The UUID of the node.
                    type: string
          
                  record:
                    description: Metadata for the volume group
                    type: object

                  snapshotGroups:
                    description: Snapshot groups that are linked to this volume group
                    items:
                      type: object
                      properties:
                        id:
                          description: ID of the snapshot group
                          type: string

                        name:
                          description: Name of the snapshot group
                          type: string
                    type: object      
                  volumes:
                    description: Volumes that are members in this volume group
                    
                    items:
                      type: object
                      properties:
                        volumeId:
                          description: ID of the member volume 
                          type: string

                        volumeName:
                          description: Name of the member volume
                          type: string
                    type: object      
              type: object
    - name: v2
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true 
      schema:       
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            hpeVolumeGroupInfos:
              description: List of HPE volume groups configured for 3PAR/Primera arrays.
              items:
                type: object
                properties:
                  uuid:
                    description: The UUID of the node.
                    type: string
          
                  record:
                    description: Metadata for the volume group
                    type: object

                  snapshotGroups:
                    description: Snapshot groups that are linked to this volume group
                    items:
                      type: object
                      properties:
                        id:
                          description: ID of the snapshot group
                          type: string

                        name:
                          description: Name of the snapshot group
                          type: string
                    type: object      
                  volumes:
                    description: Volumes that are members in this volume group
                    
                    items:
                      type: object
                      properties:
                        volumeId:
                          description: ID of the member volume 
                          type: string

                        volumeName:
                          description: Name of the member volume
                          type: string
                    type: object      
              type: object

status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---

####################################################
############  SnapshotGroupInfos Crd  ############
####################################################

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: hpesnapshotgroupinfos.storage.hpe.com
spec:
  group: storage.hpe.com
  names:
    kind: HPESnapshotGroupInfo
    plural: hpesnapshotgroupinfos
    shortNames: 
      - hpesgi
  scope: Cluster
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: false  
      schema:
        openAPIV3Schema:
          type: object
          #x-kubernetes-preserve-unknown-fields: true
          properties:
            hpeSnapshotGroupInfos:
              description: List of HPE snapshot groups created for 3PAR/Primera arrays.
              type: object
              items:
                type: object
                properties:
                  uuid:
                    description: The UUID of the node.
                    type: string
          
                  record:
                    description: Metadata for the volume group
                    type: object

                  snapshotVolumes:
                    description: Snapshot volumes that are part of this snapshot group
                    type: object
                    items:
                      type: object
                      properties:
                        srcVolumeId:
                          description: ID of the volume that is the source of this snapshot volume 
                          type: string

                        srcVolumeName:
                          description: Name of the volume that is the source of this snapshot volume
                          type: string

                        snapshotId:
                          description: Snapshot volume Id
                          type: string

                        snapshotName:
                          description: Snapshot volume name
                          type: string
    - name: v2
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true  
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            hpeSnapshotGroupInfos:
              description: List of HPE snapshot groups created for 3PAR/Primera arrays.
              type: object
              items:
                type: object
                properties:
                  uuid:
                    description: The UUID of the node.
                    type: string
          
                  record:
                    description: Metadata for the volume group
                    type: object

                  snapshotVolumes:
                    description: Snapshot volumes that are part of this snapshot group
                    type: object
                    items:
                      type: object
                      properties:
                        srcVolumeId:
                          description: ID of the volume that is the source of this snapshot volume 
                          type: string

                        srcVolumeName:
                          description: Name of the volume that is the source of this snapshot volume
                          type: string

                        snapshotId:
                          description: Snapshot volume Id
                          type: string

                        snapshotName:
                          description: Snapshot volume name
                          type: string                          

status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---

####################################################
############ HpeReplicatedDeviceInfos Crd  ############
####################################################

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: hpereplicationdeviceinfos.storage.hpe.com
spec:
  group: storage.hpe.com
  names:
    kind: HPEReplicationDeviceInfo
    plural: hpereplicationdeviceinfos
    shortNames:
      - hperdi

  scope: Cluster
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          #x-kubernetes-preserve-unknown-fields: true
          properties:
            hpeReplicationDeviceInfos:
              description: List of HPE Replicated Device Information
              type: object
              items:
                type: object
                properties:
                  targets:
                    description: List of Target Array Details
                    type: object
                    items:
                      description: Target Array Details
                      type: object
                      properties:
                        targetName: 
                          description: Target Name of the array
                          type: string
                        targetCpg:
                          description: Target CPG of the array
                          type: string
                        targetSnapCpg:
                          description: Target Snap CPG of the array
                          type: string
                        targetSecret:
                          description: Secret of the replicated array 
                          type: string
                        targetMode:
                          description: Replication Mode
                          type: string
                        targetSecretNamespace:
                          description: Namespace of secret
                          type: string
                      required:
                        - targetName
                        - targetCpg
                        - targetSecret
                        - targetSecretNamespace
    - name: v2
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            hpeReplicationDeviceInfos:
              description: List of HPE Replicated Device Information
              type: object
              items:
                type: object
                properties:
                  targets:
                    description: List of Target Array Details
                    type: object
                    items:
                      description: Target Array Details
                      type: object
                      properties:
                        targetName: 
                          description: Target Name of the array
                          type: string
                        targetCpg:
                          description: Target CPG of the array
                          type: string
                        targetSnapCpg:
                          description: Target Snap CPG of the array
                          type: string
                        targetSecret:
                          description: Secret of the replicated array 
                          type: string
                        targetMode:
                          description: Replication Mode
                          type: string
                        targetSecretNamespace:
                          description: Namespace of secret
                          type: string
                      required:
                        - targetName
                        - targetCpg
                        - targetSecret
                        - targetSecretNamespace                        
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

