scorecard:
  # Setting a global scorecard option
  # Change below to CSV bundle directory path
  bundle: /Users/raunak/test-operator/hpe-csi-driver-operator.v1.4.0
  output: json
  plugins:
    # `basic` tests configured to test HPE CSI CR
    - basic:
        cr-manifest:
          - "deploy/crds/storage.hpe.com_v1_hpecsidriver_cr.yaml"
        namespace: hpe-csi
        init-timeout: 300
    # `olm` tests configured to test HPE CSI CR
    - olm:
        cr-manifest:
          - "deploy/crds/storage.hpe.com_v1_hpecsidriver_cr.yaml"
        csv-path: "deploy/olm-catalog/hpe-csi-driver-operator/1.4.0/hpe-csi-operator.v1.4.0.clusterserviceversion.yaml"
        init-timeout: 300
        namespace: hpe-csi
