apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: manager-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hpe-csi-operator
    app.kubernetes.io/part-of: hpe-csi-operator
    app.kubernetes.io/managed-by: kustomize
  name: manager-role
rules:
  - apiGroups: ["storage.hpe.com"]
    resources: ["*"]
    verbs:
      ["get", "watch", "list", "delete", "update", "create", "patch"]
  - apiGroups: [""]
    resources:
      [
        "namespaces",
        "pods",
        "services",
        "endpoints",
        "configmaps",
        "secrets",
        "serviceaccounts",
      ]
    verbs:
      ["get", "watch", "list", "delete", "update", "create", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs:
      ["get", "watch", "list", "delete", "update", "create", "patch"]
  # CSI operator needs to create/delete a ClusterRole and ClusterRoleBinding for provisioning PVs
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      ["clusterrolebindings", "clusterroles", "roles", "rolebindings"]
    verbs:
      ["get", "watch", "list", "delete", "update", "create", "patch"]
  # On Openshift ClusterRoleBindings belong to a different apiGroup.
  - apiGroups: ["authorization.openshift.io"]
    resources: ["clusterrolebindings", "clusterroles"]
    verbs:
      ["get", "watch", "list", "delete", "update", "create", "patch"]
  # Need the same permissions as external-provisioner to be able to create it
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      ["get", "watch", "list", "delete", "update", "create", "patch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "create"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs:
      ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs:
      ["get", "watch", "list", "delete", "update", "create", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs:
      ["get", "watch", "list", "delete", "update", "create", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets"]
    verbs:
      ["get", "watch", "list", "delete", "update", "create", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs:
      ["get", "watch", "list", "delete", "update", "create", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  # Need the same permissions as external-attacher clusterrole to be able to create it
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs:
      ["get", "list", "watch", "update", "create", "delete", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  # Need the same permissions as external-snapshotter clusterrole to be able to create it
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["create", "update", "delete", "get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots/status"]
    verbs: ["update"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs:
      ["create", "update", "delete", "get", "list", "watch", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents/status"]
    verbs:
      ["create", "get", "list", "watch", "update", "delete", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  # Need the same permissions as driver-registrar clusterrole to be able to create it.
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csidrivers"]
    verbs:
      ["get", "watch", "list", "delete", "update", "create", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csidrivers"]
    verbs:
      ["get", "watch", "list", "delete", "update", "create", "patch"]
  # Need the same permissions as external-resizer to be able to create it.
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs:
      ["create", "get", "list", "watch", "update", "delete", "patch"]
  # Need permissions to let csi-driver load/unload/update hpenodeinfos resources
  - apiGroups: ["storage.hpe.com"]
    resources: ["hpenodeinfos"]
    verbs:
      ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Need permissions to let 3PAR CSP to load/unload/update hpevolumeinfos resources
  - apiGroups: ["storage.hpe.com"]
    resources: ["hpevolumeinfos"]
    verbs:
      ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["storage.hpe.com"]
    resources: ["hpereplicationdeviceinfos"]
    verbs:
      ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs:
      ["get", "watch", "list", "delete", "update", "create", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
